<div x-data="cartDrawer()" @open-cart.window="open = true" x-cloak>
    <div x-show="open" x-transition.opacity class="fixed inset-0 z-[60] bg-black/40" @click="open = false"></div>
    <aside x-show="open" x-transition:enter="transition ease-out duration-200" x-transition:enter-start="translate-x-full" x-transition:enter-end="translate-x-0" class="fixed inset-y-0 right-0 z-[61] flex w-[80vw] max-w-md flex-col bg-primary-200 p-6 shadow-2xl dark:bg-gray-400 sm:w-full" dir="{{ app()->getLocale() === 'ar' ? 'rtl' : 'ltr' }}">
        <div class="flex items-center justify-between"><h2 class="text-2xl font-semibold text-primary-700 dark:text-white">{{ __('store.cart') }}</h2><button type="button" @click="open = false" class="text-2xl text-bordo">×</button></div>
        <div x-show="!items.length" class="flex flex-1 flex-col items-center justify-center text-center text-bordo"><x-heroicon-s-shopping-cart class="h-14 w-14 mb-4" /><p>{{ __('store.empty_cart') }}</p></div>
        <div x-show="items.length" class="mt-6 flex-1 space-y-4 overflow-y-auto">
            <template x-for="item in items" :key="item.id"><div class="flex gap-3 border-b border-primary-100 pb-4 dark:border-gray-500"><img :src="item.image" class="h-16 w-16 rounded-xl object-cover" alt=""><div class="min-w-0 flex-1"><p class="truncate font-semibold text-primary-700 dark:text-white" x-text="item.name_{{ app()->getLocale() === 'ar' ? 'ar' : 'en' }} || item.name"></p><p class="text-sm text-gray-500 dark:text-gray-200" x-text="format(item.price) + ' {{ __('store.tnd') }}'"></p><span x-show="item.is_sold" class="text-sm font-semibold text-bordo">{{ __('store.sold') }}</span><div class="mt-2 flex items-center gap-2" x-show="item.has_qty && !item.is_sold"><button @click="change(item, -1)" :disabled="item.quantity <= 1" class="rounded-full bg-primary-100 px-2 disabled:opacity-40">−</button><span class="text-gray-700 dark:text-gray-100" x-text="item.quantity"></span><button @click="change(item, 1)" :disabled="item.stock !== null && item.quantity >= item.stock" class="rounded-full bg-primary-100 px-2 disabled:opacity-40">+</button></div></div><button @click="remove(item.id)" class="text-sm text-red-600">{{ __('store.remove') }}</button></div></template>
        </div>
        <div x-show="items.length" class="mt-6"><div class="mb-4 flex justify-between font-semibold text-primary-700 dark:text-white"><span>{{ __('store.subtotal') }}</span><span x-text="format(subtotal) + ' {{ __('store.tnd') }}'"></span></div><div class="flex gap-3"><button @click="clear()" class="secondary-btn flex-1">{{ __('store.empty_cart_action') }}</button><a href="{{ route('orders.checkout') }}" class="primary-btn flex-1 text-center">{{ __('store.go_to_checkout') }}</a></div></div>
    </aside>
</div>
<script>
    window.barzakhCart = window.barzakhCart || {
        key: 'barzakh-cart',
        get() { try { return JSON.parse(localStorage.getItem(this.key) || '[]'); } catch (_) { return []; } },
        save(items) { localStorage.setItem(this.key, JSON.stringify(items)); window.dispatchEvent(new CustomEvent('cart-updated')); },
        hydrate() { const current = this.get(); if (!current.length) return Promise.resolve(); const query = new URLSearchParams(); current.forEach(item => query.append('ids[]', item.id)); return fetch('{{ route('cart.products') }}?' + query.toString()).then(response => response.json()).then(catalog => { const byId = Object.fromEntries(catalog.map(product => [product.id, product])); this.save(current.map(item => ({ ...item, ...(byId[item.id] || {}), quantity: byId[item.id]?.has_qty ? Math.min(item.quantity, byId[item.id].stock ?? item.quantity) : 1 }))); }); },
        add(product, quantity = 1) { const items = this.get(); const item = items.find(i => i.id === product.id); if (item) item.quantity = product.has_qty ? Math.min(item.quantity + quantity, item.stock ?? Infinity) : 1; else items.push({...product, quantity: product.has_qty ? Math.min(quantity, product.stock ?? quantity) : 1}); this.save(items); window.dispatchEvent(new CustomEvent('open-cart')); },
        update(id, quantity) { const items = this.get(); const item = items.find(i => i.id === id); if (!item) return; item.quantity = item.has_qty ? Math.max(1, Math.min(quantity, item.stock ?? quantity)) : 1; this.save(items); },
        remove(id) { this.save(this.get().filter(i => i.id !== id)); },
        clear() { this.save([]); }
    };
    function cartDrawer() { return { open: false, items: [], init() { this.refresh(); barzakhCart.hydrate().then(() => this.refresh()); window.addEventListener('cart-updated', () => this.refresh()); }, refresh() { this.items = barzakhCart.get(); }, change(item, delta) { barzakhCart.update(item.id, item.quantity + delta); this.refresh(); }, remove(id) { barzakhCart.remove(id); this.refresh(); }, clear() { barzakhCart.clear(); this.refresh(); }, get subtotal() { return this.items.reduce((s, i) => s + Number(i.price) * i.quantity, 0); }, format(value) { return Number(value).toFixed(3); } }; }
</script>
